# Generated by Django 2.2.4 on 2019-09-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='models_id',
            new_name='user_id',
        ),
    ]
